config:
  install_tree:
    # Completely ignoring higher-level configuration options is supported with the :: notation for keys ...
    root:: $spack/../release
  # Available in v0.20.0
  source_cache: $spack/../sourcecache
  # Available in v0.20.0
  environments_root: $spack/../environments
